### ISSUE TITLE
Enhancement request: use QLVideo also for native videos

### ISSUE THREAD

**Issue by zmwangx** [Marginal/QLVideo#16]
Is it possible to let QLVideo also generate thumbnails for native videos (e.g., H.264 videos in MP4 containers)? The thumbnails generated by OS X by default seem to be the first frame. A good number of my videos begin with a black frame, or a commercial before the real program, so the first frame is often useless or even annoying. On the other hand, QLVideo seems to use a frame somewhere in the middle, which is much more reasonable. Therefore, it would be great if QLVideo also replaces the default thumbnails for native videos.

**Comment by jeanlain** [comment]
This enhancement would also help to generate thumbnails for .mov files that use codecs that are not supported by AVFoundation (but that ffmpeg supports) : sorenson, cinepack, windows media, etc. Also, many mpg files that used to have thumbnails before mavericks now have generic icons because AVFoundation is even more picky than Quicktime for mpeg playback. VLC would play those files just fine.

**Comment by zmwangx** [comment]
@jeanlain But what you mentioned don't count as "native", at least not for AVFoundation. I believe yours should be a seperate issue (although they could be solved at once, or separately).

**Comment by Marginal** [comment]
I plan in the next release to generate thumbnails for all file types derived from "public.movie", including .mov and .mp4. This will solve both @zmwangx's issue concerning the frame used to generate the thumbnail, and the issue of codecs that AVFoundation doesn't support within "native" containers (e.g. H.265 in an .ts, Sorenson in a .mov, etc).

**Comment by zmwangx** [comment]
@Marginal Sounds great!

**Comment by Marginal** [comment]
9141637 and Release 1.80 generates thumbnails for all file types derived from "public.movie", and generates a static QuickLook preview only if AVFoundation can't handle handle the file/codec combination.
Previews of Quicktime movies that AVFoundation can't handle are still weird 'though - they appear as large thumbnails instead of a full-size preview. This behaviour appears to be hard-coded into QuickLookUI so I can't fix it.
