### ISSUE TITLE
Option to enable "Matroska Cover Art" as thumbnail

### ISSUE THREAD

**Issue by enjikaka** [Marginal/QLVideo#18]
Here's some info about Matroska Cover Art: http://matroska.org/technical/cover_art/index.html

Would be nice if, instead of a frame from the movie as a thumbnail, you could choose to enable having the cover art provided in the matroska file (and of course fallback to frame if non exists).

**Comment by Marginal** [comment]
Haven't come across an mkv with cover art in the wild, but thanks for the link.

**Comment by enjikaka** [comment]
It's not very common. But a really nice feature. It's mainly used by media-centers. The windows program Icaros from Shark007 has this feature; showing cover art as thumbnails.

**Comment by enjikaka** [comment]
A nice, you integrated it!? :dancer: 

I forgot to mention there can be two types of cover art attached, portrait and landscape. Would be nice if both were supported and if you could choose to use landscape instead of portrait!

In "Icaros" you have these options; would be nice if QLVideo worked the same!
![http://i.imgur.com/WPmmPhY.png]()

**Comment by Marginal** [comment]
On OSX the thumbnailer runs as a sandboxed system process for security, so it can't see the current user's preferences.
My implementation prefers the square/portrait version over the landscape version if both are present.

**Comment by Marginal** [comment]
Release 1.81 uses embedded cover art (square/portrait in the case of mkv files with multiple cover art) to generate video thumbnails.

**Comment by enjikaka** [comment]
Awesome. My hat's off to you!

**Comment by enjikaka** [comment]
In the "Cover Flow"-view the cover art displays as expected:

![http://i.imgur.com/j1g3IUJ.jpg]()

But in the "Icon"-view the cover art gets a letterbox around it;

![http://i.imgur.com/JajvuRh.jpg]()

The "Column" view does not display the cover art at all.

Is there a way to fix that?

**Comment by Marginal** [comment]
> But in the "Icon"-view the cover art gets a letterbox around it;

Unfortunately I don't know of any way of suppressing the letterbox that gets added in Icon and List views.

> The "Column"-view does not display the cover art at all.

QuickLook supplies content in three situations:
 * Thumbnail - Shown in Finder's Icon, List and Cover Flow views.
 * Preview without seek bar -  Shown in the far right column of Finder's Column view, in Finders File -> Get Info window, and in Spotlight search results from the menubar.
 * Preview with seek bar - Shown in Finder's File -> Quick Look window.

As of version 1.81 QLVideo does this when asked by QuickLook for content:
 * Thumbnail - Supplies cover art (if present), otherwise supplies a static snapshot.
 * Preview with or without seek bar - Lets the built-in plugin supply a playable preview if it can (i.e. for various MPEG file types), otherwise supplies a static snapshot.

I'm open to the idea of supplying cover art (if present) in some more of these cases. But in which of these cases? And should it make a difference if the alternative to supplying cover art is a playable preview or a static snapshot?

**Comment by enjikaka** [comment]
> Unfortunately I don't know of any way of suppressing the letterbox that gets added in Icon and List views.

Ah okey!

> In which of these cases should the landscape version of the cover art be displayed

I think that's more of a user preference. I'd rather have the portrait version everywhere...

> Does it make a difference if the alternative to supplying cover art is a playable preview or a static snapshot?
I'd prefer if the portrait cover art is shown, if that does not exists, a static screenshot. I don't really care about playable previews.

Is it possible to add radio-boxes to the "Show View Options" panel? Would be nice if you could right click the MKV file and have something like this (bottom compartment):

![](http://i.imgur.com/HvHtVJP.png)

**Comment by Marginal** [comment]
> Is it possible to add radio-boxes to the "Show View Options" panel?

No. The thumbnailer runs as a sandboxed system process for security, so it can't see the current user's preferences (other than desired thumbnail size - and the thumbnail size is always square).

Please try this version: http://marginal.org.uk/QLVideo_182b1.pkg
* Cover art (if present) is used in all Finder and Spotlight views, for both "native" and "non-native" file types. (I never found the "Preview without seek bar" functionality for "native" file types in Finder views particularly helpful). Square/Portrait is preferred over Landscape cover art if both are present.
* Landscape cover art (if present) is used for MKVs in the QuickLook window.

**Comment by enjikaka** [comment]
Will try it out tomorrow and give feedback!

**Comment by Marginal** [comment]
Fixed in release 1.82.

**Comment by Marginal** [comment]
> But in the "Icon"-view the cover art gets a letterbox around it;

This is fixed in Release 1.83.
