### ISSUE TITLE
Provide thumbnail screenshots for each media file - Feature Request

### ISSUE THREAD

**Issue by Horatio72** [Marginal/QLVideo#23]
Hi, it would be really useful if there was an option for the screenshot associated with a media file to be made up of a grid of thumbnails from the video spread over its duration - a bit like the app 'Thumbs' does for OSX.

This would make it much easier to see the difference between clips that look similar.

**Comment by Marginal** [comment]
QuickLook previews are generated "live" e.g. when you press the space key, and it just takes too long to produce a contact sheet. ('Thumbs' doesn't have this problem because it generates contact sheets in the background, so it can take as long as it likes).

The QuickLook API has a facility (kQLPreviewPropertyCursorKey) that looks like it could be used to generate something akin to contact sheets, but it's undocumented and I haven't been able to make it work in practice.

**Comment by Marginal** [comment]
I haven't worked out how to incrementally build up the images in a contact sheet, but it turns out that the cost of generating a bunch of images isn't so high compared to the setup time to generate the first image.

So please try [v1.85](https://github.com/Marginal/QLVideo/releases/tag/rel-185). This generates a slideshow rather than a contact sheet since that seems more in line with MacOS conventions for QuickLook Previews.

The following settings entered in the Terminal can be used to customize the Preview:
 - `defaults write uk.org.marginal.qlvideo SnapshotCount -int XX` - Number of snapshots to generate. Default 10.
 - `defaults write uk.org.marginal.qlvideo SnapshotTime -int XX` - Time offset in seconds for thumbnails and single snapshots. Default 60s. (Doesn't affect already generated thumbnails - use `qlmanage -r cache` and re-start Finder to force regeneration of exisitng thumbnails).
 - `defaults write uk.org.marginal.qlvideo SnapshotAlways -bool XX` - Generate static snapshot(s) even if a playable Preview is available. Default NO.

**Comment by Horatio72** [comment]
This is a really good step forward as it makes it far easier to see the content of videos. As another option vs the contact sheet is it possible to store and display the screen grabs as an animate gif that cycles through each image in turn?

**Comment by Marginal** [comment]
It should be possible to use standard Javascript to animate through the snapshot images. But I don't know how well the integration can work - you may lose the current ability to navigate using the up or down trackpad gesture or scrollwheel.

**Comment by Marginal** [comment]
Released in [v1.86](https://github.com/Marginal/QLVideo/releases/latest).
