### ISSUE TITLE
Use embedded thumbnails (if available)

### ISSUE THREAD

**Issue by yagee-de** [Marginal/QLVideo#24]
QLVideo should use MKV embedded thumbnails/covers for preview and only generate a thumbnails if no embedded cover image is present.

**Comment by Marginal** [comment]
QLVideo uses cover art (where present) for thumbnails since [Release 1.81](https://github.com/Marginal/QLVideo/releases/tag/rel-181), and also for Finder's "Get Info" window and Spotlight results since [Release 1.82](https://github.com/Marginal/QLVideo/releases/tag/rel-182).

Check that you're using the [latest version](https://github.com/Marginal/QLVideo/releases/latest). If you're upgrading from an earlier version you will have to restart Finder after installation to see the updated thumbnails.

Otherwise, please send me a link to where I can download a MKV file that demonstrates the problem.
