### ISSUE TITLE
Removing QLVideo does not return thumbnail generation of .mp4 files to system quicklook plugin in OS 10.11

### ISSUE THREAD

**Issue by EightQuarterBit** [Marginal/QLVideo#30]
After installing QLVideo, mp4 files display as having an "MPEG-4 audio" kind when performing a "get info" from Finder, rather than the correct "MPEG-4 movie" kind.

Prior to installing QLVideo, OS 10.11 would create thumbnails and playable icon preview for .mp4 files with AAC audio and h.264 video codecs. Installing QLVideo disables this, and does not return the functionality after removing the quicklook plugin with the prescribed command, leaving the file kind as "MPEG-4 audio".

**Comment by Marginal** [comment]
QLVideo doesn't touch the file "kind" of .mp4 files

You should be able to reset the "kind" of .mp4 files by telling Launch Services to rebuild its database. Copy the following and paste into a Terminal window:
```
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -seed -domain system -domain network -domain local -domain user```

However, if the mis-assignment of the .mp4 "kind" was caused by an app, and you still have that app installed on your system, then the above won't solve it.
