### ISSUE TITLE
Feature Request: add .crm support

### ISSUE THREAD

**Issue by benyzboy8682** [Marginal/QLVideo#69]
I'm super new to GitHub so I apologize if this is posted in the wrong place. Please point me in the right direction if this is not the spot to make a feature request. 

I would like to have .crm files (Canon RAW Movie) supported by QLVideo. .crm files from the Canon EOS c200 camera contain video in the Canon Cinema RAW Light format. These clips contain 12-bit color sampling and have a resolution of 4096x2160. The files can be previewed in the Canon Cinema RAW Development application but not in the Finder. As my library of raw footage grows it is increasingly more difficult to find footage without opening files in an app like Cinema RAW Development as I can't even see a still frame in the Finder. The Finder shows these files as an executable. If there is any way to add this file type into QLVideo I would be so very grateful.

Please let me know if I can provide any further information. Thanks!

**Comment by latenitefilms** [comment]
I was kinda hoping that Canon Cinema RAW Light was included in Apple's "Pro Video Formats", so that you could just access the codec via AV Foundations, however, it seems that it actually requires (at least for support in Final Cut Pro X), the Canon RAW Plug in 1.0 for Final Cut Pro X.

See: https://support.apple.com/en-us/HT205764

I haven't looked into it properly yet, but this GitHub repository MIGHT be of assistance to someone who wants to build Canon Raw v3 (CR3) support into QLVideo:

https://github.com/lclevy/canon_cr3

Unfortunately, I don't think I have the skills to implement this myself, but happy to help test if anyone interested in tackling this issue.

**Comment by latenitefilms** [comment]
Actually, there's also [Cinema RAW Development 2.4 for macOS](https://www.usa.canon.com/internet/portal/us/home/support/details/cameras/cinema-eos/eos-c200?tab=drivers_downloads).

**Comment by Marginal** [comment]
Next release will generate thumbnails and single-image previews for Canon RAW Movie files, based on the embedded JPEG preview picture embedded in the CRM file.

**Comment by latenitefilms** [comment]
Amazing - thank you!!
